---
title: "GWAS"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GWAS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(genstats)
library(bigsnpr)
library(ggplot2)
```


Fil skabt ved 'gen_sim('example_genetic_sim_data', N=10000, M=10000, C=1000, n_sib=2)'

```{r}
setwd('C:/Users/louis/Documents/Uddannelse/Universitet/4. Semester/Dataprojekt/genstats')
genetic_data = snp_attach('100ktest.rds')
```

```{r}
G=genetic_data$genotypes
liabilities = genetic_data$fam
y = liabilities %>% select('pheno_0') 


gwas_est = GWAS(G=G, y=genetic_data$fam$pheno_0, p=0.05/10000)

```

```{r}
plot(genetic_data$map$beta, gwas_est$estim)
```


```{r}
tibble('beta'=genetic_data$map$beta, 'estim'=gwas_est$estim, 'causal_est'=gwas_est$causal_estimate) %>%
  mutate('causal'=(genetic_data$map$beta!=0)-0) %>%  
  filter(causal==1) %>%
  ggplot(aes(x=beta, y=estim)) + geom_point(aes(colour=causal_est)) + geom_abline(slope = 1)
```
```{r}

```




```{r}
tibble('beta'=genetic_data$map$beta, 'estim'=gwas_est$estim, 'causal_est'=gwas_est$causal_estimate, p_vals =gwas_est$p_vals) %>% 
  mutate('causal'=(genetic_data$map$beta!=0)-0) %>%
  ggplot(aes(x=(1:length(p_vals)), y=-log(p_vals))) + geom_point(aes(colour=causal))
```



```{r}
LTFH_fam = LTFH(genetic_data$fam, n_sib=0)
```

```{r}

LTFH_est = GWAS(G=G, y=LTFH_fam$l_g_est_0, p=0.05/10000)

tibble('beta'=genetic_data$map$beta, 'estim'=LTFH_est$estim, 'causal_est'=LTFH_est$causal_estimate, p_vals =LTFH_est$p_vals) %>% 
  mutate('causal'=(genetic_data$map$beta!=0)-0) %>%
  ggplot(aes(x=(1:length(p_vals)), y=-log(p_vals))) + geom_point(aes(colour=causal))
```

```{r}
tibble('l_estim'=LTFH_fam$l_g_est_0, 'l_g'=LTFH_fam$l_g_0) %>%
  ggplot(aes(x=l_estim, y=l_g)) + geom_point() + geom_abline(slope=1) 


```


```{r}
tibble('beta'=genetic_data$map$beta, 'estim'=LTFH_est$estim, 'causal_est'=LTFH_est$causal_estimate) %>%
  mutate('causal'=(genetic_data$map$beta!=0)-0) %>%  
  filter(causal==1) %>%
  ggplot(aes(x=beta, y=estim)) + geom_point(aes(colour=causal_est)) + geom_abline(slope = 1)
```
