---
title: "PRS"
output: html_document
date: '2022-05-25'
---

```{r}
setwd("~/Uddannelse/Universitet/4. Semester/Dataprojekt/genstats")
gen_sim(filename = "example_data", N = 100000, M = 100000, n_sib = 2, C = 1000, block_size = 500)

gen_sim(filename = "example_data_test", N = 5000, M = 100000, n_sib = 2, C = 1000, block_size = 500)
```

```{r}
library(genstats)
library(bigsnpr)
library(bigstatsr)
library(tidyverse)


setwd("~/Uddannelse/Universitet/4. Semester/Dataprojekt/genstats")
data = snp_attach("example_data.rds")



est <- genstats::LTFH(data = data, n_sib = 2) %>% 
            select(., contains("est"))

prs <- PRS_cross(data = data, y01 = est[[1]], cross_folds = 4)


prs_plot(PRS = prs, data, 'AUC')
prs_plot(PRS = prs, data, 'MSE')
prs_plot(PRS = prs, data, 'Lin_Reg')

```






```{r}


pred_model = function(train_data, y, thr, lin_reg=TRUE){
  gwas <- bigstatsr::big_univLinReg(train_data$genotypes, y.train = y)
  prs_ <- snp_PRS(G = train_data$genotypes, betas.keep =gwas$estim, lpS.keep = -predict(gwas), thr.list = thr)
  prs_ = prs_[,1]
  
  
  if (lin_reg) {model = lm(data$fam$pheno_0 ~ prs_)}
  else {model <- glm(data$fam$pheno_0 ~ prs_, family = binomial(link = "probit"))}
  
  return(list('gwas'=gwas, 'model_prs'=model))
}

m = pred_model(data, est[[1]], 3, lin_reg=FALSE)



test_set <- snp_attach("example_data_test.rds")


prediction = function(test_data, model, thr) {
  gwas = model$gwas
  model_prs = model$model_prs
  
  prs_ = snp_PRS(G = test_data$genotypes, betas.keep = gwas$estim, lpS.keep = -predict(gwas), thr.list = thr)
  probs <- predict(model_prs, data.frame('prs_' = prs_[,1]), type = "response")
  return(probs)
}



pred = prediction(test_set, m, 3)
preds = (pred > 0.5)-0


cbind('predictive positive' = preds[preds==1], 'True value'=test_set$fam$pheno_0[preds==1])


sum(test_set$fam$pheno_0[test_set$fam$pheno_0==1])
sum(preds == test_set$fam$pheno_0)
```



```{r}
df = prs %>% do.call('rbind', .)
df = df[order(as.numeric(row.names(df))),]

plot(df[,7], data$fam$pheno_0)
```

```{r}
prs <- PRS_cross(data = data, y01 = data$fam$pheno_0, cross_folds = 4)
AUC_prs_plot(prs, data = data)
MSE_prs_plot(prs, data)
```

```{r}
power_plot(GWAS(G = data$genotypes, y = est[[1]], p = 5e-7), beta = data$map$beta)
```


```{r}
power_plot(GWAS(G = data$genotypes, y = data$fam$pheno_0, p = 5e-7), beta = data$map$beta)
```


```{r}
data_test <- snp_attach("example_data_test")
prs_test <- bigsnpr::snp_PRS(G = )

model = glm(data$fam$pheno_0 ~ df[,7], family = binomial(link = "probit"))
res = predict(model, )
```

```{r}
bigsnpr::snp_PRS(G = data, betas.keep = )
```

