---
title: "PRS"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PRS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(genstats)
library(bigsnpr)
library(bigstatsr)
library(tidyverse)


data = snp_attach("genetic_data.rds")



est <- genstats::LTFH(data = data, n_sib = 2) %>% 
            select(., contains("est"))

prs <- PRS_cross(data = data, y01 = est[[1]], cross_folds = 4)


prs_plot(PRS = prs, data, 'AUC')
prs_plot(PRS = prs, data, 'MSE')
prs_plot(PRS = prs, data, 'Lin_Reg')

```






```{r}


m = pred_model(data, est[[1]], 3)



test_set <- snp_attach("genetic_data_test.rds")



pred = prediction(test_set, m, 3)
preds = (pred > 0.5)-0


cbind('predictive positive' = preds[preds==1], 'True value'=test_set$fam$pheno_0[preds==1])


sum(test_set$fam$pheno_0[test_set$fam$pheno_0==1])
sum(preds == test_set$fam$pheno_0)
```



```{r}
df = prs %>% do.call('rbind', .)
df = df[order(as.numeric(row.names(df))),]

plot(df[,7], data$fam$pheno_0)
```

```{r}
prs <- PRS_cross(data = data, y01 = data$fam$pheno_0, cross_folds = 4)
prs_plot(prs, data = data)
prs_plot(prs, data, 'AUC')
```



